# Site settings
title: Elliot Anderson
subtitle: Portfolio
email: eanderson63313@gmail.com
description: Here you will find a portfolio of some of my work. This website is very much a work in progress so does not show every single one of my projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://elliot-anderson.co.uk" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 10

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://uk.linkedin.com/in/elliot-anderson-50060488
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
