# Site settings
title: Elliot Anderson
subtitle: Portfolio
email: eanderson63313@gmail.com
description: I am a game programming student in the second year at Northumbria University, with experiance in C++. I am seeking work placement for my third year in game programming or general programming related fields.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://elliot-anderson.co.uk" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 8

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://uk.linkedin.com/in/elliot-anderson-50060488
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
